### PR TITLE
Basic Auth + SSL

### PR DESCRIPTION
**Pull request by hardwarefault**
Verify SSL certificates
Add http basic auth
Add option to skip SSL certificate verification

### CODE REVIEW

**Comment by hardwarefault** [comment]
As discussed the other day here is the patch.
It adds SSL certificate verification (optional)
It adds HTTP basic Auth and sent auth info only to your configured server.

I tested it and it's working.
Please note that android prior to 4.0 doesn't allow you to add a self signed certificate to the trusted certs, so previous version of android should disable SSL checks.

**Comment by dmstocking** [comment]
Is there logic to fall back on for pre 4.0 so it doesnt crash? If there is then I accept this pull request. BTW, be sure to add yourself to the contributes.

**Comment by hardwarefault** [comment]
Sorry for the delay, I had a very busy two weeks.
It worked before this commit for pre 4.0 but the user had to manually enable the trustAll option in preference.

With this commit I set the trustAll enabled by default.
I also added the logic to allow pre 4.0 users to trust a specific certificate the same way as with transdroid.
I tested it on JellyBean 4.2 (Gnex + Nexus 7), and with Gingerbread 2.3.x with the emulator.
I'll try on a real 2.3 device later today and let you know, but I think it's ok

**Comment by hardwarefault** [comment]
Ok, I confirm it works perfectly on a Galaxy Mini with android 2.3.x.
I'll try to port the patch to sickstache too

**Comment by dmstocking** [comment]
Ok I will test this myself but I will accept this. I havent because I dont want to break compatability with older devices.

**Comment by dmstocking** [comment]
Certificates don't actually make your server any safer. The certificate only verifies that the person your talking to is indeed who you think they are. So, your server is still exposed to the whole world, but know your positive its your server.

**Comment by dmstocking** [comment]
Well only took me 3 months ish ... but its patched!

**Comment by hardwarefault** [comment]
Thanks! I'm already using a patched version of Sickstache too. I'll fork and make a pull request for that as soon as I have time.

As said, thanks for your excellent work on those two apps :+1: !

**Comment by dmstocking** [comment]
I think tonight I am going to make these free on google play and basically hope that they are awesome and well written enough to be semi officially made the mobile app for each server. Would be nice lol.

**Comment by achmetinternet** [comment]
Can't wait! Do it now :)

**Pull request merged**
